version: "3"
services:

  nginx:
    build: ./nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"

  web:
    build: ./app
    volumes:
      - ./app:/code
    ports:
      - "5100:5100"
    command: python web.py
